name: ms_market
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  rxdart: ^0.23.1
  flutter_bloc: ^3.2.0
  equatable: ^1.0.0
  meta: ^1.1.6
  intl: ^0.16.0

  font_awesome_flutter: ^8.4.0
  shared_preferences: any
  flutter_web_auth: ^0.1.2
  http: ^0.12.0+4
  graphql_flutter: ^3.0.0-beta.2
  flutter_rating_bar: ^3.0.1+1
  image_picker: ^0.6.3+1
  dotted_border: ^1.0.4
  dio: ^3.0.8
  transparent_image: ^1.0.0
  google_maps_flutter: ^0.5.23+1
  cached_network_image: ^2.0.0
  flutter_cache_manager: ^1.1.3
  animations: ^1.0.0+3
  

 
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.4


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/logo_transparent.png"

flutter_native_splash:
  image: assets/splash.png
  color: "464d5c"

flutter:

  assets:
    - assets/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
